export const demoUser = [
  {
    id: 1,
    company: 'RMSSAAS',
    name: 'Admin',
    password: 'b',
    gender: 'Male',
    phoneNumber: '+1234567890',
    address: '123 Main Street',
    longitude: -73.935242,
    latitude: 40.73061,
    email: 'paul.jameson@example.com',
    employeeNo: 'EMP001',
    picture: 'https://randomuser.me/api/portraits/men/1.jpg',
    pictureData: null,
    verified: true,
    available: true,
    shiftAccess: true,
    branch: 'New York',
    phoneCode: '+1',
    role: 'Admin',
  },
  {
    id: 2,
    company: 'XYZ Corp.',
    name: 'Bob Johnson',
    gender: 'Male',
    phoneNumber: '+1987654321',
    address: '456 Elm Street',
    longitude: -74.006,
    latitude: 40.7128,
    email: 'bob.johnson@example.com',
    employeeNo: 'EMP002',
    picture: 'https://randomuser.me/api/portraits/men/2.jpg',
    pictureData: null,
    verified: false,
    available: false,
    shiftAccess: false,
    branch: 'Los Angeles',
    phoneCode: '+1',
    role: 'customer',
  },
  {
    id: 3,
    company: 'LMN Co.',
    name: 'Jack Smith',
    gender: 'Male',
    phoneNumber: '+1122334455',
    address: '789 Oak Street',
    longitude: -118.2437,
    latitude: 34.0522,
    email: 'jack.smith@example.com',
    employeeNo: 'EMP003',
    picture: 'https://randomuser.me/api/portraits/men/3.jpg',
    pictureData: null,
    verified: true,
    available: true,
    shiftAccess: false,
    branch: 'San Francisco',
    phoneCode: '+1',
    role: 'customer',
  },
  {
    id: 4,
    company: 'ABC Inc.',
    name: 'Sarah Johnson',
    gender: 'Female',
    phoneNumber: '+15556667777',
    address: '101 Pine Street',
    longitude: -122.4194,
    latitude: 37.7749,
    email: 'sarah.johnson@example.com',
    employeeNo: 'EMP004',
    picture: 'https://randomuser.me/api/portraits/women/4.jpg',
    pictureData: null,
    verified: true,
    available: false,
    shiftAccess: true,
    branch: 'Seattle',
    phoneCode: '+1',
    role: 'customer',
  },
  {
    id: 5,
    company: 'XYZ Corp.',
    name: 'Michael Brown',
    gender: 'Male',
    phoneNumber: '+123456789',
    address: '202 Maple Street',
    longitude: -95.3698,
    latitude: 29.7604,
    email: 'michael.brown@example.com',
    employeeNo: 'EMP005',
    picture: 'https://randomuser.me/api/portraits/men/5.jpg',
    pictureData: null,
    verified: true,
    available: true,
    shiftAccess: true,
    branch: 'Houston',
    phoneCode: '+1',
    role: 'customer',
  },
  {
    id: 5,
    company: 'XYZ Corp.',
    name: 'Michael Brown',
    gender: 'Male',
    phoneNumber: '+123456789',
    address: '202 Maple Street',
    longitude: -95.3698,
    latitude: 29.7604,
    email: 'michael.brown@example.com',
    employeeNo: 'EMP005',
    picture: 'https://randomuser.me/api/portraits/men/5.jpg',
    pictureData: null,
    verified: true,
    available: true,
    shiftAccess: true,
    branch: 'Houston',
    phoneCode: '+1',
    role: 'customer',
  },
  {
    id: 6,
    company: 'LMN Co.',
    name: 'Governor Landing',
    gender: 'Male',
    phoneNumber: '+1122334455',
    address: '789 Oak Street',
    longitude: -118.2437,
    latitude: 34.0522,
    email: 'governor.landing@example.com',
    employeeNo: 'EMP006',
    picture: 'https://randomuser.me/api/portraits/men/6.jpg',
    pictureData: null,
    verified: true,
    available: true,
    shiftAccess: true,
    branch: 'San Francisco',
    phoneCode: '+1',
    role: 'customer',
  },
  {
    id: 7,
    company: 'ABC Inc.',
    name: 'Paul Skols',
    gender: 'Male',
    phoneNumber: '+1234567890',
    address: '123 Main Street',
    longitude: -73.935242,
    latitude: 40.73061,
    email: 'paul.skols@example.com',
    employeeNo: 'EMP007',
    picture: 'https://randomuser.me/api/portraits/men/7.jpg',
    pictureData: null,
    verified: true,
    available: false,
    shiftAccess: false,
    branch: 'New York',
    phoneCode: '+1',
    role: 'customer',
  },
  {
    id: 8,
    company: 'XYZ Corp.',
    name: 'Jordan Pitch',
    gender: 'Male',
    phoneNumber: '+1987654321',
    address: '456 Elm Street',
    longitude: -74.006,
    latitude: 40.7128,
    email: 'jordan.pitch@example.com',
    employeeNo: 'EMP008',
    picture: 'https://randomuser.me/api/portraits/men/8.jpg',
    pictureData: null,
    verified: true,
    available: true,
    shiftAccess: true,
    branch: 'Los Angeles',
    phoneCode: '+1',
    role: 'customer',
  },
  {
    id: 9,
    company: 'Baka Rides',
    name: 'Agent',
    password: 'b',
    gender: 'Female',
    phoneNumber: '+1122334455',
    address: '789 Oak Street',
    longitude: -118.2437,
    latitude: 34.0522,
    email: 'emily.white@gmail.com',
    employeeNo: 'EMP009',
    picture: 'https://randomuser.me/api/portraits/women/9.jpg',
    pictureData: null,
    verified: false,
    available: true,
    shiftAccess: true,
    branch: 'San Francisco',
    phoneCode: '+1',
    role: 'Agent',
  },
  {
    id: 10,
    company: 'ABC Inc.',
    name: 'Customer',
    password: 'b',
    gender: 'Male',
    phoneNumber: '+15556667777',
    address: '101 Pine Street',
    longitude: -122.4194,
    latitude: 37.7749,
    email: 'mr.bands@gmail.com',
    employeeNo: 'EMP010',
    picture: 'https://randomuser.me/api/portraits/men/10.jpg',
    pictureData: null,
    verified: false,
    available: false,
    shiftAccess: false,
    branch: 'Seattle',
    phoneCode: '+1',
    role: 'Customer',
  },
];
